// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contactMe': string;
  'footer': string;
  'icon': string;
  'icons': string;
  'logo': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
