// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'location': string;
  'timestamp': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
