// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'atScreen': string;
  'baseTheme': string;
  'caption': string;
  'contact': string;
  'education': string;
  'event': string;
  'experience': string;
  'innerSection': string;
  'mainSection': string;
  'printDisplayNone': string;
  'printHidden': string;
  'section': string;
  'sectionHeader': string;
  'sectionHeaderText': string;
  'slide': string;
  'subTitle': string;
  'text': string;
  'title': string;
  'uppercase': string;
}
declare var cssExports: CssExports;
export = cssExports;
