// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'baseTheme': string;
  'beigeColor': string;
  'blueColor': string;
  'caption': string;
  'coralColor': string;
  'darkBlueColor': string;
  'darkCoralColor': string;
  'education': string;
  'experience': string;
  'innerSection': string;
  'lightBlueColor': string;
  'lightCoralColor': string;
  'mainSection': string;
  'sectionHeader': string;
  'subTitle': string;
  'text': string;
  'title': string;
  'uppercase': string;
}
declare var cssExports: CssExports;
export = cssExports;
