// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'list': string;
  'sectionItem': string;
}
declare var cssExports: CssExports;
export = cssExports;
