// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'angleRight': string;
  'summaryIndicator': string;
}
declare var cssExports: CssExports;
export = cssExports;
