// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'eventContent': string;
  'strv': string;
}
declare var cssExports: CssExports;
export = cssExports;
